trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-8
  masterConfig: 
    acceleratorConfig:
        count: 1
        type: NVIDIA_TESLA_T4
  # hyperparameters:
  #   goal: MINIMIZE
  #   hyperparameterMetricTag: "loss"
  #   maxTrials: 50
  #   maxParallelTrials: 0
  #   enableTrialEarlyStopping: TRUE 
  #   params:

  #   - parameterName: lr
  #     type: DOUBLE
  #     minValue:  0.0001
  #     maxValue:  0.001
  #     scaleType: UNIT_LINEAR_SCALE



